# Campfire export configuration -- all options are required.

# Export start date - the first transcript you want exported.
start_date: 2010/1/1

# Export end date - the last transcript you want exported, inclusive.
end_date:   2010/12/31

# Your Campfire API token (see "My Info" on your Campfire site).
api_token:  abababababababababababababababababababab

# Your Campfire subdomain (for 'https://myco.campfirenow.com', enter 'myco').
subdomain:  example
